### PR TITLE
Bump kramdown to 2.3.0

### PR DESCRIPTION
**Pull request by hharaguc**
Addresses a CVE: https://github.com/remind101/r101-api/network/alert/Gemfile.lock/kramdown/open

#### Related To
https://github.com/remind101/r101-api/pull/15114
https://github.com/remind101/r101-api/pull/15119
https://github.com/kramdown/parser-gfm

#### Test Plan
- [x] Run `bundle exec rake` locally

### CODE REVIEW

**Comment by virtue3** [comment]
@hharaguc what would be really helpful is what the major change is between 1.x and 2.x and if there is anything we are using is breaking?

**Comment by hharaguc** [comment]
@virtue3 it looked like the biggest difference was that they moved the GFM parser out of the kramdown distribution (https://github.com/kramdown/parser-gfm#kramdown-gfm-parser). it looks like [this](https://github.com/remind101/grape-swagger/blob/2d5a63c8a3507bbb96fc136ce6100ef26b9a315a/lib/grape-swagger.rb#L198) is the only place we use kramdown. this line will fail to recognize the GFM input with the kramdown bump to 2.x if we don't add the parser too (you can see this in the CI output for the r101-api dependabot PR (here)[https://app.circleci.com/pipelines/github/remind101/r101-api/2114/workflows/22b3757d-270d-47c4-a4c8-6efac6db9b3e/jobs/181178])

**Comment by virtue3** [comment]
Yeah I think we're goign to need to add that GFM parser and include it at the top of the file?

**Comment by hharaguc** [comment]
@virtue3 yep! latest commit should take care of that

**Comment by virtue3** [comment]
I think you need to bump the `.gemspec` file as well

**Comment by hharaguc** [comment]
paired with @virtue3 on this, we're down to give it a whirl. even if things hit the fan, this will only block deployments (which are already blocked by the CVE) - this won't affect prod since there's already a built image for it

**Pull request merged**
